package com.cryptoCurrencyApp

object Versions {
    const val LIFECYCLE = "2.6.0"
    const val CORE = "1.9.0"
    const val APPCOMPAT = "1.6.1"
    const val MATERIAL = "1.8.0"
    const val MEDIAROUTER = "1.3.1"
    const val PAGING = "3.1.1"
    const val COIL = "2.2.2"
    const val LOTTIE = "3.4.0"
    const val RETROFIT = "2.9.0"
    const val GSON = "2.8.9"
    const val ROOM = "2.5.0"
    const val COMPOSE_UI = "1.3.3"
    const val COMPOSE_UI_TOOLING = "1.4.0-rc01"
    const val KOIN = "3.2.0"
    const val JUNIT = "4.13.2"
    const val KOTLINX_COROUTINES_TEST = "1.6.4"
    const val ESPRESSO_CORE = "3.5.1"
    const val COMPILER = "1.4.3"
    const val NAVIGATION_COMPOSE = "2.5.3"
    const val ACTIVITY_COMPOSE = "1.6.1"
    const val FOUNDATION = "1.3.1"
    const val CORE_KTX = "1.9.0"
    const val ANDROIDX_JUNIT = "1.1.5"
    const val GLIDE = "4.13.2"
    const val KOTLINX_COROUTINES_ANDROID = "1.6.4"
    const val OKHTTP_LOGGING_INTERCEPTOR = "5.0.0-alpha.2"
    const val MOCKK = "1.13.4"
    const val RUNTIME_LIVEDATA = "1.3.3"
}
